"""Next-best-action candidate generation, ranking, and tie-break (FR-010,
FR-011, FR-012). Deterministic and pure — no AI/LLM involvement in eligibility
or ranking (Constitution Principle I); an LLM may only personalize the
message of an *already-finalized* NBA, downstream of this module
(spec.md FR-013, tasks.md T101a).
"""

from concierge.decisioning.models import ActivitySnapshot, NBACandidate
from concierge.domain.enums import ActivityStatus

# FR-011 base priorities. BILLING_RENEWAL_READINESS is intentionally not
# generated by candidate generation in this MVP slice (no billing/renewal
# provider data wired yet) but is listed for completeness/documentation.
BASE_PRIORITY = {
    "ACTIVATION_FAILURE": 100,
    "NUMBER_TRANSFER_FAILURE": 95,
    "NETWORK_FAILURE": 90,
    "REQUIRED_SECURITY_INCOMPLETE": 70,
    "BILLING_RENEWAL_READINESS": 65,
    "AUTOPAY_AUTO_RECHARGE_GAP": 60,
    "APP_GAP": 50,
    "VOICEMAIL_GAP": 40,
    "PROTECTION_DECISION_GAP": 30,
    "PREMIUM_FEATURE": 20,
}

# FR-012 tie-break order: critical issue > required setup > billing/renewal >
# digital adoption > optional adoption. Lower rank = more urgent category.
TIE_BREAK_CATEGORY = {
    "ACTIVATION_FAILURE": 0,
    "NUMBER_TRANSFER_FAILURE": 0,
    "NETWORK_FAILURE": 0,
    "REQUIRED_SECURITY_INCOMPLETE": 1,
    "BILLING_RENEWAL_READINESS": 2,
    "AUTOPAY_AUTO_RECHARGE_GAP": 3,
    "APP_GAP": 3,
    "VOICEMAIL_GAP": 3,
    "PROTECTION_DECISION_GAP": 4,
    "PREMIUM_FEATURE": 4,
}

APP_GAP_DAY_THRESHOLD = 3
VOICEMAIL_GAP_DAY_THRESHOLD = 5
AUTOPAY_GAP_DAY_THRESHOLD = 7
PROTECTION_DECISION_DAY_THRESHOLD = 10


def _candidate(line_id: str, action_code: str, reason_codes: list[dict]) -> NBACandidate:
    return NBACandidate(
        line_id=line_id,
        action_code=action_code,
        priority=BASE_PRIORITY[action_code],
        tie_break_rank=TIE_BREAK_CATEGORY[action_code],
        reason_codes=reason_codes,
    )


def generate_candidates(line_id: str, activities: list[ActivitySnapshot], journey_day: int) -> list[NBACandidate]:
    """Every currently-eligible NBA candidate for one line (FR-010, FR-011)."""
    by_code = {a.activity_code: a for a in activities}
    candidates: list[NBACandidate] = []

    def _status(code: str) -> ActivityStatus | None:
        a = by_code.get(code)
        return a.status if a is not None else None

    if _status("SIM_ESIM_ACTIVATION") == ActivityStatus.FAILED:
        candidates.append(
            _candidate(
                line_id,
                "ACTIVATION_FAILURE",
                [{"code": "ACTIVATION_FAILURE", "label": "Device activation failed", "deduction": None}],
            )
        )

    if _status("NUMBER_TRANSFER") == ActivityStatus.FAILED:
        candidates.append(
            _candidate(
                line_id,
                "NUMBER_TRANSFER_FAILURE",
                [{"code": "NUMBER_TRANSFER_FAILURE", "label": "Number transfer failed", "deduction": None}],
            )
        )

    if _status("NETWORK_VALIDATION") == ActivityStatus.FAILED:
        candidates.append(
            _candidate(
                line_id,
                "NETWORK_FAILURE",
                [{"code": "NETWORK_FAILURE", "label": "Network validation failed", "deduction": None}],
            )
        )

    security_status = _status("ACCOUNT_SECURITY")
    if security_status is not None and security_status not in (ActivityStatus.COMPLETED, ActivityStatus.NOT_APPLICABLE):
        candidates.append(
            _candidate(
                line_id,
                "REQUIRED_SECURITY_INCOMPLETE",
                [{"code": "REQUIRED_SECURITY_INCOMPLETE", "label": "Account security not yet set up", "deduction": None}],
            )
        )

    autopay_like = [by_code[c] for c in ("AUTOPAY_PAYMENT_SETUP", "AUTO_RECHARGE_SETUP") if c in by_code]
    if (
        journey_day > AUTOPAY_GAP_DAY_THRESHOLD
        and autopay_like
        and all(a.status != ActivityStatus.COMPLETED for a in autopay_like)
    ):
        candidates.append(
            _candidate(
                line_id,
                "AUTOPAY_AUTO_RECHARGE_GAP",
                [{"code": "AUTOPAY_AUTO_RECHARGE_INCOMPLETE", "label": "AutoPay/auto-recharge not set up", "deduction": None}],
            )
        )

    app_status = _status("APP_ADOPTION")
    if journey_day > APP_GAP_DAY_THRESHOLD and app_status is not None and app_status != ActivityStatus.COMPLETED:
        candidates.append(
            _candidate(
                line_id,
                "APP_GAP",
                [{"code": "APP_NOT_ADOPTED", "label": "Mobile app not downloaded", "deduction": None}],
            )
        )

    voicemail_status = _status("VOICEMAIL_SETUP")
    if (
        journey_day > VOICEMAIL_GAP_DAY_THRESHOLD
        and voicemail_status is not None
        and voicemail_status != ActivityStatus.COMPLETED
    ):
        candidates.append(
            _candidate(
                line_id,
                "VOICEMAIL_GAP",
                [{"code": "VOICEMAIL_NOT_CONFIGURED", "label": "Voicemail not configured", "deduction": None}],
            )
        )

    protection_status = _status("DEVICE_PROTECTION_DECISION")
    if (
        journey_day > PROTECTION_DECISION_DAY_THRESHOLD
        and protection_status == ActivityStatus.NOT_STARTED
    ):
        candidates.append(
            _candidate(
                line_id,
                "PROTECTION_DECISION_GAP",
                [{"code": "PROTECTION_DECISION_PENDING", "label": "Device protection decision pending", "deduction": None}],
            )
        )

    premium_status = _status("PREMIUM_FEATURE_ADOPTION")
    if premium_status == ActivityStatus.NOT_STARTED:
        candidates.append(
            _candidate(
                line_id,
                "PREMIUM_FEATURE",
                [{"code": "PREMIUM_FEATURE_AVAILABLE", "label": "Eligible premium feature available", "deduction": None}],
            )
        )

    return candidates


def rank_candidates(candidates: list[NBACandidate], tie_break_key=lambda c: c.line_id) -> list[NBACandidate]:
    """Sorts by base priority (desc), then FR-012's tie-break category (asc),
    then a final deterministic key so ranking is always reproducible even
    when priority *and* category are identical (e.g. the same critical issue
    on two different lines, per Clarifications Q2 / checklist CHK009)."""
    return sorted(candidates, key=lambda c: (-c.priority, c.tie_break_rank, tie_break_key(c)))


def filter_escalation_suppressed(
    candidates: list[NBACandidate], suppressed_action_codes: frozenset[str] = frozenset()
) -> list[NBACandidate]:
    """FR-028a: exclude candidates whose issue already has an open
    EscalationCase, so the concierge never recommends something already
    handed to a human."""
    if not suppressed_action_codes:
        return candidates
    return [c for c in candidates if c.action_code not in suppressed_action_codes]


def current_nba_for_line(
    activities: list[ActivitySnapshot], journey_day: int, suppressed_action_codes: frozenset[str] = frozenset()
) -> NBACandidate | None:
    """The single top-ranked NBA for one line, or None if nothing is eligible."""
    candidates = generate_candidates("", activities, journey_day)
    candidates = filter_escalation_suppressed(candidates, suppressed_action_codes)
    ranked = rank_candidates(candidates)
    return ranked[0] if ranked else None
